### ISSUE TITLE
code & pre tags (developer issues)

### ISSUE THREAD

**Issue by nicolasdanelon** [kalvn/Shaarli-Material#29]
Hi kalv,
I'm using shaarli in the place I work. Sometimes we need to shaare code. Or store it as a `wiki` like post.. I create a little css code is in the `extra.html` file and goes like this:
```css
.markdown pre {
	background-color: #eee;
	padding: 4px 9px;
	border-radius: 4px;
	overflow: auto;
	box-shadow: 0 -1px 0 #e5e5e5,0 0 1px rgba(0,0,0,.12),0 1px 2px rgba(0,0,0,.24);
}

.markdown pre code {
	color: black;
	font-family: Consolas, Monaco, 'Andale Mono', monospace;
	direction: ltr;
	text-align: left;
	white-space: pre;
	word-spacing: normal;
	word-break: normal;
	line-height: 1.7;
	font-size: 11.5px;
	-moz-tab-size: 4;
	-o-tab-size: 4;
	tab-size: 4;
	-webkit-hyphens: none;
	-moz-hyphens: none;
	-ms-hyphens: none;
	hyphens: none;	
}
```

So.. It may be a little improvement for your awesome theme, right? thank you so much for the `extra.html` file! it's awesomeeeEEEEEEE !!!!

![screen shot 2016-02-15 at 12 03 17](https://cloud.githubusercontent.com/assets/2846046/13052406/776e27e6-d3dd-11e5-9619-71e42841c966.png)
