### ISSUE TITLE
Dark variation possible?

### ISSUE THREAD

**Issue by sigmap** [kalvn/Shaarli-Material#67]
Would it be possible to the replace the white/light backgrounds and black/dark text with the inverse? White text and dark backgrounds?

**Comment by kalvn** [comment]
That's not an easy thing to do according to how the theme is built. Therefore, it's not planed to add such variation for the moment.

What you can do though, if you know a bit of CSS, is to use the `user.css` file [to add a few rules](https://github.com/shaarli/Shaarli/wiki/Theming#custom-css) to remove dark backgrounds. This is a short example:

```css
body {
    background: #333;
    color: #ddd;
}
.link-outer, .link-footer{
    background: #666;
}
.link-outer, .link-header a{
    color: #ddd;
}
```
