### ISSUE TITLE
Config value for setting main font?

### ISSUE THREAD

**Issue by dajare** [kalvn/Shaarli-Material#68]
I have used the instructions in the README.md file for the theme to set the colours to the "Indigo" set from the [suggested swatches][s]. Success! :) I would also like to set the **font** to one of my choice, but I can't work out how to do that. I tried simply changing the choice in the [`_values.scss` file][v], but that didn't work. 

Is there a **config.MATERIAL_FONT** type setting one can use in the `config.json.php` file? I see that these configuration settings are used in `material/includes.html`, but I don't see any way of customizing the font. So -- how can the font be customized?

Thanks!

[s]: https://material.io/guidelines/style/color.html#color-color-palette
[v]: https://github.com/kalvn/Shaarli-Material/blob/master/material/scss/components/_values.scss#L2

**Comment by dajare** [comment]
After trying to see what is involved, it is possible that allowing for completely free font customization might be non-trivial.

If so, what about at least giving a choice between Roboto (default, as it is at present), and [Roboto Slab][r] -- so users could at least have a choice between a "sans" and a "serif" option? For me, that would do the trick nicely!

For comparision, here's Roboto:

![sans](http://www.androidpolice.com/wp-content/uploads/2013/03/nexusae0_robotosans.png)

And here's Roboto Slab:

![serif](http://www.androidpolice.com/wp-content/uploads/2013/03/nexusae0_robotoslabbig.png)

[r]: https://www.fontsquirrel.com/fonts/roboto-slab

**Comment by kalvn** [comment]
Thanks for your suggestion.

I like your idea but I don't want to offer too many options in order to keep the maintenability easy and to avoid too many modifications of Shaarli's configuration file. At least not until theme parameters are officially supported.

What you can do though is to use the famous `user.css` which allows you to add additional CSS rules.

You must create a file named `user.css` in the `<shaarli_location>/data` directory of your installation. To enable it, you must update your version of *Shaarli Material* to the very last one of the master branch (I just did a fix to properly include this file). In the file, you can for example paste the following content:

```css
@font-face {
  font-family: 'RobotoSlab';
  font-style: normal;
  font-weight: 100;
  src: url('roboto-slab/RobotoSlab-Thin.ttf') format('truetype');
}
@font-face {
  font-family: 'RobotoSlab';
  font-style: normal;
  font-weight: 200;
  src: url('roboto-slab/RobotoSlab-Light.ttf') format('truetype');
}
@font-face {
  font-family: 'RobotoSlab';
  font-style: normal;
  font-weight: 400;
  src: url('roboto-slab/RobotoSlab-Regular.ttf') format('truetype');
}
@font-face {
  font-family: 'RobotoSlab';
  font-style: normal;
  font-weight: 700;
  src: url('roboto-slab/RobotoSlab-Bold.ttf') format('truetype');
}

body{
    font-family: RobotoSlab, Roboto, serif;
}
```

Then you need of course to [download Roboto Slab font](https://fonts.google.com/specimen/Roboto+Slab?selection.family=Roboto+Slab). You must unzip the content of the archive so that you have the following organisation:

- ...
- /data
  - ...
  - user.css
  - roboto-slab
     - RobotoSlab-Bold.ttf
     - RobotoSlab-Light.ttf
     - RobotoSlab-Regular.ttf
     - RobotoSlab-Thin.ttf

I just tested and it works well :)
